[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "EB7YTFKkpkm9SFfUbLZdRTGxRD5dX6C1ndPkAurbfrbk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/droigon/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
